# Generated by Django 5.0.2 on 2024-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='reportitem',
            name='report_quantity',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
