# Generated by Django 5.0.2 on 2024-03-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='reports.client'),
        ),
    ]
