# Generated by Django 5.0.2 on 2024-03-19 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.item', unique=True),
        ),
    ]
