# Generated by Django 5.0.2 on 2024-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_report',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='info',
            field=models.CharField(blank=True, default='', help_text='Infotext au survol', max_length=50),
        ),
    ]
