# Generated by Django 5.0.2 on 2024-03-19 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_reportitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitem',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.item'),
        ),
        migrations.AlterUniqueTogether(
            name='reportitem',
            unique_together={('report', 'item')},
        ),
    ]
