# Generated by Django 5.0.2 on 2024-04-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_client_phone_number1'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
